### ISSUE TITLE
Wrap 'type Server Raw' in a newtype?

### ISSUE THREAD

**Issue by mf59816** [haskell-servant/servant-server#26]
Julian and I played with pushing state through routes into handlers [https://gist.github.com/jkarni/18c56c0b9bcafc1e55a3, linked here: https://github.com/haskell-servant/servant-server/pull/21].

This works well until 'Raw' endpoints come into play, because of this:

    instance HasServer Raw where
        type Server Raw = Application

`Application` is an alias for `Request -> (Response -> IO ResponseReceived) -> IO ResponseReceived`, so the `PushReaderT` instance for `a -> b` matches.  I could write an instance for `IO ResponseReceived` and get some functionality back.  But if i want to push `EitherT` instead of `ReaderT`, I want to use the continuation in order to construct different responses for left and right, and then I am stuck.

A solution would be simple:

    newtype RawApplication = RawApplication { fromRawApplication :: Application }

    instance HasServer Raw where
        type Server Raw = RawApplication

There would be some incompatibility, but a migration guide would be easy to write and trivial to follow.  I am happy to provide the pull requests, but I would like to hear what you think before I start.

**Comment by jkarni** [comment]
This is a good point I hadn't thought about. I think my inclination (as I feel like it's become with all `EitherT`-related issues) is to just leave this issue open until we've gotten a much better sense for the lay of the land (especially since as a temporary hack, writing your own `Raw` wrapper, and committing to not using `Raw` itself should work). If it turns out pushing these type synonyms proves to be the best approach, this is probably a good idea; if it turns out there's something better, this seems like an unnecessary complication.

**Comment by mf59816** [comment]
Writing your own `Raw` wrapper is a good idea that somehow escaped me.  Thanks.

Also I agree with everything you say here.

**Comment by jkarni** [comment]
Closing till we figure out whether the answer to #11 makes this irrelevant.
