### ISSUE TITLE
`ReqBody String` seems to be broken

### ISSUE THREAD

**Issue by martin-huschenbett** [haskell-servant/servant-server#44]
When I use a request body which contains only a string, I always get the following error when making a request:

> HTTP POST request failed with status: 400 - Bad Request

Here's a minimal example for reproducing the error with `servant-0.2.2`, `servant-server-0.2.4`, `servant-client-0.2.2` and `ghc-7.10.1`:

```haskell
type MiniAPI = ReqBody String :> Post()

miniAPI :: Proxy MiniAPI
miniAPI = Proxy

runServer = run 8015 (serve miniAPI $ liftIO . print)

runClient = runEitherT (client miniAPI "test" url) >>= print
    where Right url = parseBaseUrl "http://localhost:8015"
```

When I change the request body to `(String,String)`, everything works just fine.

**Comment by jkarni** [comment]
`aeson` by default doesn't allow top-level strings (correctly, according to http://www.ietf.org/rfc/rfc4627.txt?number=4627, but also somewhat annoyingly). The upcoming release relaxes this requirement for better or worse; for now I'd wrap it up in a newtype with a record, since that works, and moreover is considered good practice (because (a) you can never extend an endpoint that expects a string in a backwards-compatible way, and (b) not all libraries support top-level JSON strings).

**Comment by martin-huschenbett** [comment]
Oh, I didn't known about this. Thank you and sorry.
