### ISSUE TITLE
I need trailing '/' in URLs to be ignored.

### ISSUE THREAD

**Issue by mf59816** [haskell-servant/servant-server#5]
If route `/bla` works as expected, `/bla/` responds with `not found`.  Not sure if this is intended, but I need to allow trailing '/' to meet non-negotiable protocol specs.

I will try to come up with a patch soon.  Please let me know if you are willing to consider merging this, and if you want the behavior to be configurable.

**Comment by jkarni** [comment]
Yeah, I think 90% of frameworks ignore trailing slashes, although there are exceptions (in PHP-land?). I'm in favor of ignoring them. @alpmestan ?

**Comment by alpmestan** [comment]
This pretty much "was intended", meaning I was aware of that. However, none of my code will break if we make servant treat `/bla` and `/bla/` the same, and if this is something you need I'm all for making that happen.

Regarding whether we want to make this configurable, well, can you think of a situation where what you suggest would cause problems for users? If yes, then I suppose making this configurable would be nice. Otherwise I'd suggest not worrying too much about that.

**Comment by mf59816** [comment]
No good reason for making it configurable.  Just the idea that as it would be nicer to not need trailing '/', it would be nice, too, to disable it unless it's really needed.
